version: "3.8"
services:
  eureka-service:
    container_name: eureka-service
    image: eureka-image
    ports:
      - "8761:8761"
  salaries-service:
    container_name: salaries-service
    image: salaries-image
    ports:
      - "31231:8181"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
    links:
      - eureka-service
      
  
      