version: "3.8"
services:
  config-service:
    container_name: config-service
    build: ./micro-services/config-service
    ports:
      - '8081:8081'
  eureka-service:
    container_name: eureka-service
    build: ./micro-services/eureka-service
    depends_on:
      - config-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8081
    ports:
      - '8761:8761'
      
  
      