spring:
  application:
    name: salaries-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
server:
  port: 8181
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}