server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uploadtimestamps-service
          uri: lb://uploadtimestamps-service
          predicates:
              Path=/timestamps/**,/uploadtimestamps/**

        - id: salaries-service
          uri: lb://salaries-service
          predicates:
            - Path=/salaries/**
            - Path=/staff/**
        - id: uploadextrahours-service
          uri: lb://uploadextrahours-service
          predicates:
            - Path=/uploadextrahours/**
            - Path=/extrahours/**

        - id: uploadjustification-service
          uri: lb://uploadjustification-service
          predicates:
            - Path=/uploadjustification/**
            - Path=/justification/**